model_dim: 256
num_heads: 8
seghit_processor_num_layers: 2
latent_len: 128
track_encoder_num_layers: 2
dropout_p: 0.0
widening_factor: 4


module:
  _target_: deepmuonreco.nn.MuonDetLatentAttnModel
  track_dim: ${exp.track_dim}
  segment_dim: ${exp.segment_dim}
  rechit_dim: ${exp.rechit_dim}
  output_dim: ${exp.target_dim}

  model_dim: ${model.model_dim}
  num_heads: ${model.num_heads}

  seghit_processor_num_layers: ${model.seghit_processor_num_layers}
  latent_len: ${model.latent_len}
  track_encoder_num_layers: ${model.track_encoder_num_layers}
  dropout_p: ${model.dropout_p}
  widening_factor: ${model.widening_factor}


in_keys:
  - track
  - [pad_masks, track]
  - segment
  - [pad_masks, segment]
  - rechit
  - [pad_masks, rechit]

out_keys:
  - logits
