name: deepmuonreco-py312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch-gpu=2.7.0
  - tensordict=0.8.3
  - einops=0.8.1
  - lightning=2.5.1.post0
  - torchmetrics=1.7.3
  - aim
  - h5py
  - uproot
  - hist
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - ipykernel
  - omegaconf=2.3.0
  - hydra-core=1.3.2
  - hydra-colorlog
  - coolname
  - python-htcondor
