# @package _global_

defaults:
  - default

data:
  root: ${paths.root_dir}/data
  train_file: sanity-check.root
  val_file: sanity-check.root
  test_file: sanity-check.root
  predict_file: sanity-check.root
  batch_size: 32
