# @package _global_

fit:
  num_epochs: 2

data:
  train_set:
    path: ${paths.root_dir}/data/sanity-check.root
    max_events: ${data.batch_size}

  val_set:
    path: ${paths.root_dir}/data/sanity-check.root
    max_events: ${data.eval_batch_size}

  test_set:
    path: ${paths.root_dir}/data/sanity-check.root
    max_events: ${data.eval_batch_size}
