track: [
    'px', 'py', 'pz',
    'charge',
]

segment: [
    'pos_x', 'pos_y', 'pos_z',
    'dir_x', 'dir_y', 'dir_z',
]

hit: [
    'pos_x', 'pos_y', 'pos_z',
]


preprocessing:
  track_log: # signeld log1p
    offset: [0, 0, 0, 0]
    scale: [5, 5, 5, 1]

  segment:
    offset: [0, 0, 0, 0, 0, 0]
    scale: [750, 720, 1000, 1, 1, 1]

  hit:
    offset: [0, 0, 0]
    scale: [750, 720, 1000]
