modules:

  # NOTE: track
  - name: track_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: ${feature_set.preprocessing.track.offset}
      scale: ${feature_set.preprocessing.track.scale}
    in_keys:
      - track
    out_keys:
      - track_prep

  # NOTE: segment
  - name: seg_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: ${feature_set.preprocessing.segment.offset}
      scale: ${feature_set.preprocessing.segment.scale}
    in_keys:
      - segment
    out_keys:
      - segment_prep

  # NOTE: hit
  - name: hit_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: ${feature_set.preprocessing.hit.offset}
      scale: ${feature_set.preprocessing.hit.scale}
    in_keys:
      - rechit
    out_keys:
      - rechit_prep
