modules:

  # NOTE: track: [px, py, pz, q]

  - name: track_log
    module:
      _target_: deepmuonreco.nn.SignedLog1p
      index: [0, 1, 2] # apply to px, py, pz
    in_keys:
      - track
    out_keys:
      - track_prep

  - name: track_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: [0, 0, 0, 0]
      scale: [5, 5, 5, 1]
    in_keys:
      - track_prep
    out_keys:
      - track_prep

  # NOTE: segment: [pos_x, pos_y, pos_z, dir_x, dir_y, dir_z]

  - name: seg_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: [0, 0, 0, 0, 0, 0]
      scale: [750, 720, 1000, 1, 1, 1]
    in_keys:
      - segment
    out_keys:
      - segment_prep

  # NOTE: hit

  - name: hit_norm
    module:
      _target_: deepmuonreco.nn.Normalize
      offset: [0, 0, 0]
      scale: [750, 720, 1000]
    in_keys:
      - rechit
    out_keys:
      - rechit_prep
