# @package _global_

defaults:
  - _self_

  - exp: default
  - paths: default
  - data: default

  - augmentation: none
  - preprocessing: default
  - model: vanilla_transformer
  - postprocessing: default

  - metric: default

  - criterion: bce
  - criterion_reduction: masked_mean

  - optimizer: adamw
  - lr_scheduler: plateau

  - trainer: gpu
  - callbacks: default
  - logger: aim

  - misc: default

  - hydra: default
  - debug: null
