# @package _global_

defaults:
  - _self_

  - exp: default
  - paths: default
  - data: default

  - augmentation: none
  - preprocessing: ${exp}
  - model: latent_attention
  - postprocessing: default

  - metric: default

  - criterion: bce
  - criterion_reduction: masked_mean

  - optimizer: adamw
  - lr_scheduler: plateau

  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim

  - misc: default

  - torch: default
  - hydra: default
  - debug: null
