# @package _global_

defaults:
  - _self_

  - exp: tracker_track_selection
  - paths: default
  - data: default # define datamodule, which builds datasets, dataloaders, and samplers
  - feature_set: pqv # feature set

  - augmentation: none
  - preprocessing: tracker_track_log_minmax # signed log1p for track
  - model: latent_attention
  - postprocessing: default

  - metric: default

  - criterion: bce
  - criterion_reduction: masked_mean

  - optimizer: adamw
  - lr_scheduler: plateau

  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim

  - misc: default

  - torch: default
  - hydra: default
  - debug: null
