# @package _global_

defaults:
  - _self_

  - exp: tracker_track_selection
  - paths: default

  - datamodule: default
  - feature_set: pqv

  - augmentation: none
  - preprocessing: tracker-track-log_minmax
  - model: latent_attention
  - postprocessing: default

  - criterion: bce

  - optimizer: adamw
  - lr_scheduler: plateau

  - metric: default

  - trainer: gpu_16-mixed
  - callbacks: default
  - logger: aim

  - run: default

  - torch: default
  - hydra: default
  - debug: null
