name: test # experiment name
pos_weight: 30.0

track_feature_list: [
    'px', 'py', 'pz',
]

segment_feature_list: [
    'pos_x', 'pos_y', 'pos_z',
    'dir_x', 'dir_y', 'dir_z',
]

hit_feature_list: [
    'pos_x', 'pos_y', 'pos_z',
]

track_dim: ${eval:'len(${.track_feature_list})'}
segment_dim: ${eval:'len(${.segment_feature_list})'}
hit_dim: ${eval:'len(${.hit_feature_list})'}
target_dim: 1
